# Generated by Django 6.0.5 on 2026-05-10 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('run_command', models.CharField(blank=True, max_length=200)),
                ('test_command', models.CharField(blank=True, max_length=200)),
                ('lint_command', models.CharField(blank=True, max_length=200)),
                ('style_command', models.CharField(blank=True, max_length=200)),
                ('devicon', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'technologies',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=5)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.technology')),
            ],
            options={
                'ordering': ['language', 'technology__key'],
                'unique_together': {('technology', 'language')},
            },
        ),
    ]
