# Generated by Django 6.0.5 on 2026-05-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_populate_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='latest_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='technology',
            name='version_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='version_source',
            field=models.CharField(blank=True, help_text='Registro para buscar versão: pypi:nome, npm:nome, github:owner/repo, cargo:nome, rubygems:nome', max_length=200),
        ),
    ]
